/**
 * A crawler's-eye audit of the public pages: what one fetched page says about
 * itself (`extractPageFacts`), and what is wrong with it alone or next to the
 * others (`auditPages`).
 *
 * Two callers share it, so the rules are written once: the SEO health page in
 * the admin panel, which crawls this deployment's sitemap on demand, and the
 * end-to-end crawl (e2e/seo.spec.ts), which fails the suite on any error.
 *
 * The HTML is our own, generated by Next, so the extraction is done with
 * patterns rather than a DOM library: the tags it reads have one shape. It is
 * deliberately literal about what it finds; a page that hides its title in a
 * script is a page a crawler would also miss.
 *
 * Besides the usual checks (status, title, description, canonical, robots,
 * one H1, Open Graph, structured data, alt text) it looks for things a public
 * page must never contain: API keys, webhook secrets, signing links with
 * their token, and private document URLs.
 */
import { validateJsonLdInHtml } from "./validate-jsonld"

export type PageFacts = {
  url: string
  status: number
  title: string | null
  description: string | null
  canonical: string | null
  robots: string | null
  xRobotsTag: string | null
  lang: string | null
  h1: string[]
  ogTitle: string | null
  ogImage: string | null
  twitterCard: string | null
  viewport: boolean
  hreflang: { lang: string; href: string }[]
  jsonLdTypes: string[]
  jsonLdErrors: string[]
  internalLinks: string[]
  imagesWithoutAlt: number
  leaks: string[]
}

export type Issue = { url: string; severity: "error" | "warning"; message: string }

const decode = (s: string) =>
  s.replace(/&amp;/g, "&").replace(/&quot;/g, '"').replace(/&#x27;|&#39;/g, "'").replace(/&lt;/g, "<").replace(/&gt;/g, ">").trim()

function attr(tag: string, name: string): string | null {
  const m = new RegExp(`\\s${name}="([^"]*)"`, "i").exec(tag)
  return m ? decode(m[1]) : null
}

function metaContent(head: string, key: "name" | "property", value: string): string | null {
  for (const m of head.matchAll(/<meta\b[^>]*>/gi)) {
    if (attr(m[0], key)?.toLowerCase() === value) return attr(m[0], "content")
  }
  return null
}

/** What must never appear in a public page's HTML. */
const LEAK_PATTERNS: [RegExp, string][] = [
  [/\bsk_(live|test)_[A-Za-z0-9]{8,}/, "a Stripe secret key"],
  [/\bwhsec_[A-Za-z0-9]{8,}/, "a webhook signing secret"],
  [/\bre_[A-Za-z0-9]{16,}/, "a Resend API key"],
  [/\bAC[0-9a-f]{32}\b/, "a Twilio account SID"],
  [/\/sign\/[A-Za-z0-9_-]{32}\b/, "a signing link with its token"],
  [/\/api\/documents\/[a-z0-9]{20,}\/(original|signed)/, "a private document URL"],
  // Removed: [/better-auth\.session_token/, "a session cookie name"]. A
  // cookie's *name* is public (the cookie policy lists it, as it should);
  // only its value is secret, and that never reaches HTML.
]

export function extractPageFacts(html: string, url: string, status: number, headers: { get(name: string): string | null }): PageFacts {
  const origin = new URL(url).origin
  const head = /<head[^>]*>([\s\S]*?)<\/head>/i.exec(html)?.[1] ?? html
  const title = /<title[^>]*>([\s\S]*?)<\/title>/i.exec(head)?.[1]
  const canonicalTag = [...head.matchAll(/<link\b[^>]*>/gi)].map((m) => m[0]).find((t) => attr(t, "rel") === "canonical")
  const hreflang = [...head.matchAll(/<link\b[^>]*>/gi)]
    .map((m) => m[0])
    .filter((t) => attr(t, "rel") === "alternate" && attr(t, "hreflang"))
    .map((t) => ({ lang: attr(t, "hreflang")!, href: attr(t, "href")! }))
  const body = html.slice(html.search(/<body/i))
  const h1 = [...body.matchAll(/<h1\b[^>]*>([\s\S]*?)<\/h1>/gi)].map((m) => decode(m[1].replace(/<[^>]+>/g, " ").replace(/\s+/g, " ")))
  const links = new Set<string>()
  for (const m of body.matchAll(/<a\b[^>]*\shref="([^"#][^"]*)"/gi)) {
    try {
      const target = new URL(decode(m[1]), url)
      if (target.origin === origin && !target.pathname.startsWith("/_next")) links.add(target.pathname)
    } catch {
      // mailto:, tel: and malformed hrefs are not internal links.
    }
  }
  const images = [...body.matchAll(/<img\b[^>]*>/gi)].map((m) => m[0])
  const visible = html.replace(/<script[^>]*src=[^>]*><\/script>/gi, "")
  const leaks = LEAK_PATTERNS.filter(([re]) => re.test(visible)).map(([, what]) => what)
  const jsonLd = validateJsonLdInHtml(html, url)

  return {
    url,
    status,
    title: title ? decode(title) : null,
    description: metaContent(head, "name", "description"),
    canonical: canonicalTag ? attr(canonicalTag, "href") : null,
    robots: metaContent(head, "name", "robots"),
    xRobotsTag: headers.get("x-robots-tag"),
    lang: /<html\b[^>]*\slang="([^"]+)"/i.exec(html)?.[1] ?? null,
    h1,
    ogTitle: metaContent(head, "property", "og:title"),
    ogImage: metaContent(head, "property", "og:image"),
    twitterCard: metaContent(head, "name", "twitter:card"),
    viewport: metaContent(head, "name", "viewport") !== null,
    hreflang,
    jsonLdTypes: jsonLd.types,
    jsonLdErrors: jsonLd.errors,
    internalLinks: [...links].sort(),
    imagesWithoutAlt: images.filter((img) => attr(img, "alt") === null).length,
    leaks,
  }
}

/** Indexable unless a robots meta tag or header says otherwise. */
export function isIndexable(facts: Pick<PageFacts, "robots" | "xRobotsTag">): boolean {
  return !/noindex/i.test(`${facts.robots ?? ""} ${facts.xRobotsTag ?? ""}`)
}

const norm = (u: string) => u.replace(/\/+$/, "") || u

/**
 * Problems with each page and across them. `expectIndexable` are the URLs
 * the sitemap submits: each must be indexable, canonical to itself and 200.
 */
export function auditPages(pages: PageFacts[], options: { expectIndexable?: Set<string> } = {}): Issue[] {
  const issues: Issue[] = []
  const add = (url: string, severity: Issue["severity"], message: string) => issues.push({ url, severity, message })

  for (const p of pages) {
    const submitted = options.expectIndexable?.has(p.url) ?? true
    if (p.status !== 200) add(p.url, "error", `answers ${p.status}`)
    for (const leak of p.leaks) add(p.url, "error", `HTML contains ${leak}`)
    if (p.status !== 200) continue

    if (!p.title) add(p.url, "error", "no <title>")
    else if (p.title.length > 65) add(p.url, "warning", `title is ${p.title.length} characters; search results cut around 60`)
    if (!p.description) add(p.url, "error", "no meta description")
    else if (p.description.length < 50 || p.description.length > 165) add(p.url, "warning", `description is ${p.description.length} characters (aim for 70-160)`)
    if (!p.lang) add(p.url, "error", "<html> has no lang")
    if (!p.viewport) add(p.url, "error", "no viewport meta tag (mobile rendering)")
    if (p.imagesWithoutAlt > 0) add(p.url, "error", `${p.imagesWithoutAlt} image(s) without an alt attribute`)
    for (const e of p.jsonLdErrors) add(p.url, "error", `structured data: ${e}`)

    if (submitted) {
      if (!isIndexable(p)) add(p.url, "error", "in the sitemap but marked noindex")
      if (!p.canonical) add(p.url, "error", "no canonical link")
      else if (norm(p.canonical) !== norm(p.url)) add(p.url, "error", `canonical points elsewhere: ${p.canonical}`)
      if (p.h1.length !== 1) add(p.url, "error", `${p.h1.length} <h1> elements (expected 1)`)
      if (!p.ogTitle || !p.ogImage) add(p.url, "warning", "missing og:title or og:image (share previews)")
      if (!p.twitterCard) add(p.url, "warning", "no twitter:card")
    }
  }

  const indexable = pages.filter((p) => p.status === 200 && isIndexable(p))
  for (const field of ["title", "description"] as const) {
    const by = new Map<string, string[]>()
    for (const p of indexable) {
      const v = p[field]
      if (v) by.set(v, [...(by.get(v) ?? []), p.url])
    }
    for (const [value, urls] of by) {
      if (urls.length > 1) for (const url of urls) add(url, "error", `${field} "${value.slice(0, 60)}" is shared with ${urls.filter((u) => u !== url).join(", ")}`)
    }
  }
  return issues
}

/** Sitemap URLs from a sitemap.xml body, with their lastmod when present. */
export function parseSitemap(xml: string): { loc: string; lastmod: string | null }[] {
  return [...xml.matchAll(/<url>([\s\S]*?)<\/url>/g)].map((m) => ({
    loc: decode(/<loc>([\s\S]*?)<\/loc>/.exec(m[1])?.[1] ?? ""),
    lastmod: /<lastmod>([\s\S]*?)<\/lastmod>/.exec(m[1])?.[1] ?? null,
  }))
}
